#!/usr/bin/env bash
# Create /var/run/myscript.pid containing the script's PID

echo $$ > /var/run/myscript.pid

# Handle signals
trap "echo 'I hate the kill command'; exit 0" SIGTERM
trap "echo 'Y U no love me?!'; exit 0" SIGINT
trap "rm -f /var/run/myscript.pid; exit 0" SIGQUIT SIGTERM

# Display To infinity and beyond indefinitely
while true; do
  echo "To infinity and beyond"
  sleep 2
done

