#!/usr/bin/env bash
#displays the content of the file /etc/passwd.


# Open the file in read mode
while IFS=":" read -r username password userid groupid name home shell; do
  # Display the username, user id, and home directory path
  echo "Username: $username"
  echo "User ID: $userid"
  echo "Home Directory: $home"
  echo ""
done < /etc/passwd

