#!/usr/bin/env bash
#displays the content of the file /etc/passwd,
#	using the while loop + IFS.


# Set the IFS variable to ":"
IFS=":"

# Open the file in read mode
while read -r username password userid groupid name home shell; do
  # Display the information in the desired format
  echo "The user $username is part of the $groupid gang, lives in $home and rides $shell."
  echo "User ID's place is protected by the passcode $password,"
  echo "more info about the user here: $userid $name"
  echo ""
done < /etc/passwd

