#!/usr/bin/env bash
#displays Best School 10 times using while loop and Hi after 9th loop.


count=1
while ((count <= 10)); do
	if [ $count == 9 ]; then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	count=$((count + 1))

done
