#!/usr/bin/env bash
#loops from 1 to 10 and implements conditional statements


i=1

while ((i <= 20)); do
  echo "$i"
  case $i in
    4) echo "Bad luck from China" ;;
    9) echo "Bad luck from Japan" ;;
    17) echo "Bad luck from Italy" ;;
  esac
  (( i++ ))
done

