#!/bin/env bash
# displays the content of the current directory
#In a list format
#only part of the name after the first dash is displayed


for file in *; do
   if [[ "$file" =~ ^\. ]]; then
      continue
   fi
   echo "${file##*-}"
done


