#!/bin/env bash
# displays the content of the current directory
#In a list format
#only part of the name after the first dash is displayed


list=$(ls)
for file in $list; do
  filename=$(echo "$file" | cut -d'-' -f2-)
  echo "$filename"
done


