#!/bin/env bash
# displays the content of the current directory
#In a list format
#only part of the name after the first dash is displayed


for file in *; do
  # Check if file is not hidden
  if [[ "$file" != .* ]]; then
    # Split the file name on the first dash and display only the second part
    file_name=$(echo "$file" | cut -d'-' -f2-)
    echo "$file_name"
  fi
done

